version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      ga:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    groups:
      maven:
        patterns:
          - "*"
