CMD := "./mvnw -T 1C"

default:
    just -l

mvn +ARGS:
    {{ CMD }} {{ ARGS }}

version-check:
    {{ CMD }} versions:display-dependency-updates versions:display-plugin-updates versions:display-property-updates

javadoc:
    {{ CMD }} compile javadoc:javadoc
    open ./target/dokka/html/index.html

qcheck:
    docker run --rm -it -p 8080:8080 \
        -v ./:/data/project/ \
        -v ./tmp/qres:/data/results/ \
        jetbrains/qodana-jvm-community:latest --show-report

fmt: apply
apply:
    {{ CMD }} spotless:apply

check: verify
verify:
    {{ CMD }} verify

test:
    {{ CMD }} test

run: exec
exec:
    {{ CMD }} compile exec:java

compile:
    {{ CMD }} compile

jar: package
package:
    {{ CMD }} package

native-exe: native-package
native-package:
    {{ CMD }} -Pnative package

prod:
    {{ CMD }} -V clean verify --file pom.xml
    {{ CMD }} -V package --file pom.xml

install:
    {{ CMD }} install

clean:
    {{ CMD }} clean
